{% set name = "fs" %}
{% set version = "2.4.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c10ba188b14d6213a1ca950efd004931abbfa64b294c80bbf1045753831bf42f

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - appdirs >=1.4.3,<2
    - pytz
    - six >=1.10.0,<2
    - enum34 >=1.1.6,<2  # [py2k]
    - scandir >=1.5,<2  # [py2k or py34]
    - typing ==3.6.4  # [py2k or py34]
    - backports.os ==0.1.1  # [py2k]

test:
  imports:
    - fs
    - fs.opener

about:
  home: https://www.pyfilesystem.org/
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Filesystem abstraction layer for Python
  description: pyfilesystem2 lets you work with diverse filesystems through a common API.
  doc_url: https://docs.pyfilesystem.org/en/v{{ version }}
  dev_url: https://github.com/PyFilesystem/pyfilesystem2

extra:
  recipe-maintainers:
    - notestaff
    - willmcgugan
    - ReimarBauer
