{% set name = "fs" %}
{% set version = "2.0.18" %}
{% set hash_type = "sha256" %}
{% set hash_value = "2dc289f911e426e18a7009d7b57e6cfc0aafab06d2a95e1d9469ed3ec3c45889" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    
  run:
    - python
    - setuptools
    - appdirs >=1.4.3,<2
    - pytz
    - six >=1.10.0,<2
    - enum34 >=1.1.6,<2  # [py2k]
    - scandir >=1.5,<2  # [py2k or py34]

test:
  imports:
    - fs
    - fs.opener

about:
  home: https://www.pyfilesystem.org/
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Filesystem abstraction layer for Python
  description: "pyfilesystem2 lets you work with diverse filesystems through a common API."
  doc_url: https://docs.pyfilesystem.org/en/v{{ version }}
  dev_url: 'https://github.com/PyFilesystem/pyfilesystem2'

extra:
  recipe-maintainers: 
    - notestaff
    - willmcgugan
    - ReimarBauer
